Repository SABS-R3-Epidemiology/epiabm, pull requests merged in 2021-12, with the labels that each got.

#1 Initial Commit
  .github/workflows/cpp-coverage.yml
  .github/workflows/cpp-unit-tests-ubuntu.yml
  .gitignore
  README.md
  cEpiabm/CMakeLists.txt
  cEpiabm/cmake/Catch.cmake
  cEpiabm/cmake/CatchAddTests.cmake
  cEpiabm/cmake/CompilerWarnings.cmake
  cEpiabm/cmake/ProjectSettings.cmake
  cEpiabm/cmake/Sanitisers.cmake
  cEpiabm/cmake/StaticAnalysers.cmake
  cEpiabm/cmake/epiabm-config.cmake
  cEpiabm/src/CMakeLists.txt
  cEpiabm/src/covidsim.cpp
  cEpiabm/src/covidsim.hpp
  cEpiabm/src/dataclasses/cell.cpp
  cEpiabm/src/dataclasses/cell.hpp
  cEpiabm/src/dataclasses/household.cpp
  cEpiabm/src/dataclasses/household.hpp
  cEpiabm/src/dataclasses/membersInterface.cpp
  cEpiabm/src/dataclasses/membersInterface.hpp
  cEpiabm/src/dataclasses/microcell.cpp
  cEpiabm/src/dataclasses/microcell.hpp
  cEpiabm/src/dataclasses/person.cpp
  cEpiabm/src/dataclasses/person.hpp
  cEpiabm/src/dataclasses/place.cpp
  cEpiabm/src/dataclasses/place.hpp
  cEpiabm/src/dataclasses/population.cpp
  cEpiabm/src/dataclasses/population.hpp
  cEpiabm/src/population_factory.cpp
  cEpiabm/src/population_factory.hpp
  cEpiabm/test/CMakeLists.txt
  cEpiabm/test/catch/catch.hpp
  cEpiabm/test/catch_main.cpp
  cEpiabm/test/dataclasses/test_cell.cpp
  cEpiabm/test/dataclasses/test_household.cpp
  cEpiabm/test/dataclasses/test_microcell.cpp
  cEpiabm/test/dataclasses/test_person.cpp
  cEpiabm/test/dataclasses/test_place.cpp
  cEpiabm/test/dataclasses/test_population.cpp
  cEpiabm/test/test_population_factory.cpp
Labels: enhancement, C++

#18 Pop config
  pyEpiabm/docs/source/routines.rst
  pyEpiabm/pyEpiabm/__init__.py
  pyEpiabm/pyEpiabm/abstract_sweep.py
  pyEpiabm/pyEpiabm/cell.py
  pyEpiabm/pyEpiabm/covidsim_helpers.py
  pyEpiabm/pyEpiabm/host_progression_sweep.py
  pyEpiabm/pyEpiabm/household.py
  pyEpiabm/pyEpiabm/household_sweep.py
  pyEpiabm/pyEpiabm/microcell.py
  pyEpiabm/pyEpiabm/parameters.py
  pyEpiabm/pyEpiabm/person.py
  pyEpiabm/pyEpiabm/population.py
  pyEpiabm/pyEpiabm/tests/test_household.py
  pyEpiabm/pyEpiabm/tests/test_microcell.py
  pyEpiabm/pyEpiabm/tests/test_toy_population_config.py
  pyEpiabm/pyEpiabm/toy_population_config.py
  pyEpiabm/run_tests.py
  pyEpiabm/setup.py
Labels: enhancement, python

#23 CompartmentCounter for tracking number of people in each compartment
  pyEpiabm/docs/source/core.rst
  pyEpiabm/pyEpiabm/__init__.py
  pyEpiabm/pyEpiabm/_compartment_counter.py
  pyEpiabm/pyEpiabm/cell.py
  pyEpiabm/pyEpiabm/microcell.py
  pyEpiabm/pyEpiabm/person.py
  pyEpiabm/pyEpiabm/population.py
  pyEpiabm/pyEpiabm/tests/test_cell.py
  pyEpiabm/pyEpiabm/tests/test_compartment_counter.py
  pyEpiabm/pyEpiabm/tests/test_microcell.py
  pyEpiabm/pyEpiabm/tests/test_person.py
  pyEpiabm/pyEpiabm/tests/test_population.py
  pyEpiabm/run_tests.py
Labels: enhancement, python

#27 C++ Logging Classes
  cEpiabm/src/CMakeLists.txt
  cEpiabm/src/dataclasses/household.hpp
  cEpiabm/src/logfile.cpp
  cEpiabm/src/logfile.hpp
  cEpiabm/src/output_folder_handler.cpp
  cEpiabm/src/output_folder_handler.hpp
  cEpiabm/test/CMakeLists.txt
  cEpiabm/test/test_log_file.cpp
  cEpiabm/test/test_output_file_handler.cpp
Labels: enhancement, C++

#35 Docs link
  .github/workflows/cpp-unit-tests-ubuntu.yml
  .github/workflows/os-tests.yml
  .github/workflows/unit-tests.yml
  LICENSE.md
  README.md
  pyEpiabm/requirements.txt
Labels: bug, frontend
