Repository SABS-R3-Epidemiology/epiabm, pull requests merged in 2022-09, with the labels that each got.

#147 Py py2c population converter
  .coveragerc
  pyEpiabm/docs/source/utility.rst
  pyEpiabm/pyEpiabm/utility/__init__.py
  pyEpiabm/pyEpiabm/utility/py2c_population.py
Labels: enhancement, C++, python

#145 Py age new cases writer
  pyEpiabm/docs/source/outputs.rst
  pyEpiabm/pyEpiabm/output/__init__.py
  pyEpiabm/pyEpiabm/output/age_stratified_new_cases_writer.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_output/test_age_stratified_new_cases_writer.py
Labels: enhancement, python

#148 Cpp documentation
  README.md
  cEpiabm/docs/conf.py
  cEpiabm/docs/configuration.rst
  cEpiabm/docs/dataclasses.rst
  cEpiabm/docs/index.rst
  cEpiabm/docs/reporters.rst
  cEpiabm/docs/simulations.rst
  cEpiabm/docs/sweeps.rst
  cEpiabm/docs/utilities.rst
  cEpiabm/src/configuration/config_factory_interface.hpp
  cEpiabm/src/configuration/host_progression_config.hpp
  cEpiabm/src/configuration/infection_config.hpp
  cEpiabm/src/configuration/json_factory.cpp
  cEpiabm/src/configuration/json_factory.hpp
  cEpiabm/src/configuration/simulation_config.hpp
  cEpiabm/src/dataclasses/cell.cpp
  cEpiabm/src/dataclasses/cell.hpp
  cEpiabm/src/dataclasses/compartment_counter.cpp
  cEpiabm/src/dataclasses/compartment_counter.hpp
  cEpiabm/src/dataclasses/household.cpp
  cEpiabm/src/dataclasses/household.hpp
  cEpiabm/src/dataclasses/microcell.cpp
  cEpiabm/src/dataclasses/microcell.hpp
  cEpiabm/src/dataclasses/person.cpp
  cEpiabm/src/dataclasses/person.hpp
  cEpiabm/src/dataclasses/place.cpp
  cEpiabm/src/dataclasses/place.hpp
  cEpiabm/src/dataclasses/population.cpp
  cEpiabm/src/dataclasses/population.hpp
  cEpiabm/src/reporters/cell_compartment_reporter.cpp
  cEpiabm/src/reporters/cell_compartment_reporter.hpp
  cEpiabm/src/reporters/percell_compartment_reporter.cpp
  cEpiabm/src/reporters/percell_compartment_reporter.hpp
  cEpiabm/src/reporters/population_compartment_reporter.cpp
  cEpiabm/src/reporters/population_compartment_reporter.hpp
  cEpiabm/src/reporters/timestep_reporter_interface.cpp
  cEpiabm/src/reporters/timestep_reporter_interface.hpp
  cEpiabm/src/simulations/basic_simulation.cpp
  cEpiabm/src/simulations/basic_simulation.hpp
  cEpiabm/src/simulations/threaded_simulation.cpp
  cEpiabm/src/simulations/threaded_simulation.hpp
  cEpiabm/src/sweeps/basic_host_progression_sweep.cpp
  cEpiabm/src/sweeps/basic_host_progression_sweep.hpp
Labels: documentation, C++

#146 fixed output filename
  pyEpiabm/pyEpiabm/output/_csv_dict_writer.py
  pyEpiabm/pyEpiabm/output/_csv_writer.py
  pyEpiabm/pyEpiabm/output/abstract_reporter.py
  pyEpiabm/pyEpiabm/routine/simulation.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_output/test_age_stratified_new_cases_writer.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_output/test_csv_dict_writer.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_output/test_csv_writer.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_output/test_new_cases_writer.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_routine/test_simulation.py
Labels: bug, python

#152 Additional python bindings
  cEpiabm/src/python_bindings/bind_dataclasses.hpp
  pyEpiabm/pyEpiabm/utility/py2c_population.py
Labels: enhancement, C++, python

#155 Debugging seed determinism
  pyEpiabm/pyEpiabm/core/cell.py
  pyEpiabm/pyEpiabm/core/household.py
  pyEpiabm/pyEpiabm/core/microcell.py
  pyEpiabm/pyEpiabm/core/place.py
  pyEpiabm/pyEpiabm/core/population.py
  pyEpiabm/pyEpiabm/property/spatial_foi.py
  pyEpiabm/pyEpiabm/routine/file_population_config.py
  pyEpiabm/pyEpiabm/routine/simulation.py
  pyEpiabm/pyEpiabm/sweep/update_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_unit/test_routine/test_simulation.py
  python_examples/gibraltar_example/gibraltar_flow.py
  python_examples/gibraltar_example/gibraltar_parameters.json
  python_examples/gibraltar_example/simulation_outputs/age_stratify.png
  python_examples/gibraltar_example/simulation_outputs/gibraltar_weeky_cases.csv
  python_examples/gibraltar_example/simulation_outputs/output_gibraltar.csv
  python_examples/gibraltar_example/simulation_outputs/simulation_flow_SIR_plot.png
Labels: bug, python

#156 new cpp writer and py spatial foi fix
  cEpiabm/src/CMakeLists.txt
  cEpiabm/src/python_bindings/bind_dataclasses.hpp
  cEpiabm/src/python_bindings/bind_reporters.hpp
  cEpiabm/src/reporters/age_stratified_population_reporter.cpp
  cEpiabm/src/reporters/age_stratified_population_reporter.hpp
  cEpiabm/src/sweeps/host_progression_sweep.cpp
  cEpiabm/src/sweeps/host_progression_sweep.hpp
  cEpiabm/test/CMakeLists.txt
  cEpiabm/test/reporters/test_age_stratified_population_reporter.cpp
  pyEpiabm/pyEpiabm/utility/py2c_population.py
Labels: enhancement, C++, python
