Repository SABS-R3-Epidemiology/epiabm, pull requests merged in 2022-03, with the labels that each got.

#74 Py test instructions
  LICENSE.md
  pyEpiabm/README.md
  pyEpiabm/docs/source/conf.py
  pyEpiabm/pyEpiabm/tests/__init__.py
  pyEpiabm/pyEpiabm/version_info.py
  pyEpiabm/run_tests.py
Labels: python

#88 Py editor config
  .editorconfig
  .flake8
  .gitignore
Labels: python, frontend

#87 Documentation refactorisation
  .gitignore
  pyEpiabm/docs/source/conf.py
  pyEpiabm/pyEpiabm/core/_compartment_counter.py
  pyEpiabm/pyEpiabm/core/cell.py
  pyEpiabm/pyEpiabm/core/household.py
  pyEpiabm/pyEpiabm/core/microcell.py
  pyEpiabm/pyEpiabm/core/parameters.py
  pyEpiabm/pyEpiabm/core/person.py
  pyEpiabm/pyEpiabm/core/place.py
  pyEpiabm/pyEpiabm/core/population.py
  pyEpiabm/pyEpiabm/output/_csv_dict_writer.py
  pyEpiabm/pyEpiabm/output/_csv_writer.py
  pyEpiabm/pyEpiabm/output/abstract_reporter.py
  pyEpiabm/pyEpiabm/property/infection_status.py
  pyEpiabm/pyEpiabm/property/place_type.py
  pyEpiabm/pyEpiabm/routine/abstract_population_config.py
  pyEpiabm/pyEpiabm/routine/file_population_config.py
  pyEpiabm/pyEpiabm/routine/household_infection.py
  pyEpiabm/pyEpiabm/routine/place_infection.py
  pyEpiabm/pyEpiabm/routine/simulation.py
  pyEpiabm/pyEpiabm/routine/spatial_infection.py
  pyEpiabm/pyEpiabm/routine/toy_population_config.py
  pyEpiabm/pyEpiabm/sweep/abstract_sweep.py
  pyEpiabm/pyEpiabm/sweep/host_progression_sweep.py
  pyEpiabm/pyEpiabm/sweep/household_sweep.py
  pyEpiabm/pyEpiabm/sweep/initial_infected_sweep.py
  pyEpiabm/pyEpiabm/sweep/place_sweep.py
  pyEpiabm/pyEpiabm/sweep/queue_sweep.py
  pyEpiabm/pyEpiabm/sweep/spatial_sweep.py
  pyEpiabm/pyEpiabm/sweep/update_place_sweep.py
  pyEpiabm/pyEpiabm/utility/distance_metrics.py
  pyEpiabm/pyEpiabm/utility/exception_logger.py
  pyEpiabm/pyEpiabm/utility/inverse_cdf.py
  pyEpiabm/pyEpiabm/utility/random_methods.py
  pyEpiabm/pyEpiabm/utility/state_transition_matrix.py
  python_examples/spatial_example/voronoi_plotting_example.py
Labels: documentation, enhancement

#93 Py timestep unification
  pyEpiabm/pyEpiabm/routine/household_infection.py
  pyEpiabm/pyEpiabm/routine/place_infection.py
  pyEpiabm/pyEpiabm/routine/simulation.py
  pyEpiabm/pyEpiabm/routine/spatial_infection.py
  pyEpiabm/pyEpiabm/sweep/host_progression_sweep.py
  pyEpiabm/pyEpiabm/sweep/household_sweep.py
  pyEpiabm/pyEpiabm/sweep/place_sweep.py
  pyEpiabm/pyEpiabm/sweep/spatial_sweep.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_household_forces.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_place_forces.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_simulation.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_space_forces.py
Labels: python, refactor

#95 Docs installation in README (#94)
  README.md
Labels: bug, documentation

#99 Py infection forces
  pyEpiabm/docs/source/properties.rst
  pyEpiabm/docs/source/routines.rst
  pyEpiabm/pyEpiabm/core/__init__.py
  pyEpiabm/pyEpiabm/core/parameters.py
  pyEpiabm/pyEpiabm/core/person.py
  pyEpiabm/pyEpiabm/property/__init__.py
  pyEpiabm/pyEpiabm/property/household_foi.py
  pyEpiabm/pyEpiabm/property/personal_foi.py
  pyEpiabm/pyEpiabm/property/place_foi.py
  pyEpiabm/pyEpiabm/property/spatial_foi.py
  pyEpiabm/pyEpiabm/routine/__init__.py
  pyEpiabm/pyEpiabm/sweep/host_progression_sweep.py
  pyEpiabm/pyEpiabm/sweep/household_sweep.py
  pyEpiabm/pyEpiabm/sweep/initial_infected_sweep.py
  pyEpiabm/pyEpiabm/sweep/place_sweep.py
  pyEpiabm/pyEpiabm/sweep/spatial_sweep.py
  pyEpiabm/pyEpiabm/tests/test_core/test_person.py
  pyEpiabm/pyEpiabm/tests/test_property/test_household_foi.py
  pyEpiabm/pyEpiabm/tests/test_property/test_personal_foi.py
  pyEpiabm/pyEpiabm/tests/test_property/test_place_foi.py
  pyEpiabm/pyEpiabm/tests/test_property/test_space_foi.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_host_progression_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_household_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_initial_infected_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_spatial_sweep.py
Labels: enhancement, python

#102 Py cell foi
  pyEpiabm/pyEpiabm/core/parameters.py
  pyEpiabm/pyEpiabm/property/place_foi.py
  pyEpiabm/pyEpiabm/property/spatial_foi.py
  pyEpiabm/pyEpiabm/tests/test_property/test_place_foi.py
  pyEpiabm/pyEpiabm/tests/test_property/test_space_foi.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_spatial_sweep.py
Labels: enhancement, python

#104 Py doc test
  pyEpiabm/docs/source/outputs.rst
  pyEpiabm/docs/source/sweeps.rst
  pyEpiabm/docs/source/utility.rst
  pyEpiabm/run_tests.py
Labels: bug, documentation

#111 Py community
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: frontend

#113 Py age distribution
  pyEpiabm/pyEpiabm/core/parameters.py
  pyEpiabm/pyEpiabm/core/person.py
  pyEpiabm/pyEpiabm/property/personal_foi.py
  pyEpiabm/pyEpiabm/property/spatial_foi.py
  pyEpiabm/pyEpiabm/tests/test_core/test_person.py
  pyEpiabm/pyEpiabm/utility/distance_metrics.py
  pyEpiabm/pyEpiabm/utility/state_transition_matrix.py
  python_examples/simulation_flow.py
Labels: enhancement, python

#115 Py Age Dependent Host Progression
  pyEpiabm/pyEpiabm/core/parameters.py
  pyEpiabm/pyEpiabm/core/person.py
  pyEpiabm/pyEpiabm/property/spatial_foi.py
  pyEpiabm/pyEpiabm/sweep/host_progression_sweep.py
  pyEpiabm/pyEpiabm/sweep/initial_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_core/test_parameters.py
  pyEpiabm/pyEpiabm/tests/test_core/test_person.py
  pyEpiabm/pyEpiabm/tests/test_property/test_space_foi.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_host_progression_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_initialise_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_utility/test_state_transition_matrix.py
  pyEpiabm/pyEpiabm/tests/test_utility/test_transition_time_matrix.py
  pyEpiabm/pyEpiabm/utility/state_transition_matrix.py
  pyEpiabm/pyEpiabm/utility/transition_time_matrix.py
Labels: enhancement, python

#118 Py profiler
  .gitignore
  CONTRIBUTING.md
  pyEpiabm/pyEpiabm/sweep/place_sweep.py
Labels: enhancement, frontend

#106 Infectiousness progression
  pyEpiabm/pyEpiabm/core/person.py
  pyEpiabm/pyEpiabm/sweep/host_progression_sweep.py
  pyEpiabm/pyEpiabm/sweep/initial_infected_sweep.py
  pyEpiabm/pyEpiabm/tests/parameter_config_tests.py
  pyEpiabm/pyEpiabm/tests/test_core/test_person.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_file_population_config.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_toy_population_config.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_host_progression_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_household_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_initial_infected_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_initialise_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_queue_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_update_place_sweep.py
  pyEpiabm/pyEpiabm/tests/test_utility/test_inverse_cdf.py
  pyEpiabm/pyEpiabm/tests/test_utility/test_state_transition_matrix.py
  pyEpiabm/pyEpiabm/tests/test_utility/test_transition_time_matrix.py
  pyEpiabm/pyEpiabm/tests/testing_parameters.json
  python_examples/simple_parameters.json
  python_examples/spatial_example/spatial_parameters.json
Labels: enhancement, python

#121 Py working sim
  README.md
  pyEpiabm/pyEpiabm/core/cell.py
  pyEpiabm/pyEpiabm/core/microcell.py
  pyEpiabm/pyEpiabm/routine/file_population_config.py
  pyEpiabm/pyEpiabm/sweep/host_progression_sweep.py
  pyEpiabm/pyEpiabm/sweep/initial_infected_sweep.py
  pyEpiabm/pyEpiabm/tests/test_core/test_cell.py
  pyEpiabm/pyEpiabm/tests/test_core/test_microcell.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_file_population_config.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_host_progression_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_initial_infected_sweep.py
  python_examples/spatial_example/spatial_simulation_flow.py
  python_examples/spatial_example/voronoi_plotting_example.py
Labels: bug, python
