Repository SABS-R3-Epidemiology/epiabm, pull requests merged in 2022-02, with the labels that each got.

#52 Py mock issue
  pyEpiabm/pyEpiabm/output/_csv_dict_writer.py
  pyEpiabm/pyEpiabm/output/_csv_writer.py
  pyEpiabm/pyEpiabm/tests/test_output/test_csv_dict_writer.py
  pyEpiabm/pyEpiabm/tests/test_output/test_csv_writer.py
Labels: bug, python

#54 Py spatial plotter
  pyEpiabm/pyEpiabm/core/cell.py
  pyEpiabm/pyEpiabm/routine/simulation.py
  pyEpiabm/pyEpiabm/routine/toy_population_config.py
  pyEpiabm/pyEpiabm/tests/test_core/test_cell.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_simulation.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_toy_population_config.py
  python_examples/README.md
  python_examples/spatial_example/spatial_outputs/output.csv
  python_examples/spatial_example/spatial_outputs/spatial_flow_Icurve_plot.png
  python_examples/spatial_example/spatial_outputs/voronoi_animation.gif
  python_examples/spatial_example/spatial_outputs/voronoi_grid_img.png
  python_examples/spatial_example/spatial_simulation_flow.py
  python_examples/spatial_example/voronoi_plotting_example.py
Labels: enhancement, python, frontend

#60 Fixes to cpp spatial sweeps
  cEpiabm/src/CMakeLists.txt
  cEpiabm/src/covidsim.cpp
  cEpiabm/src/dataclasses/cell.cpp
  cEpiabm/src/dataclasses/cell.hpp
  cEpiabm/src/sweeps/spatial_sweep.cpp
  cEpiabm/test/CMakeLists.txt
  cEpiabm/test/sweeps/test_spatial_sweep.cpp
  cEpiabm/test/test_covidsim.cpp
Labels: bug, C++

#55 C++ Spatial Sweep
  cEpiabm/src/CMakeLists.txt
  cEpiabm/src/covidsim.cpp
  cEpiabm/src/covidsim.hpp
  cEpiabm/src/dataclasses/cell.cpp
  cEpiabm/src/dataclasses/cell.hpp
  cEpiabm/src/sweeps/spatial_sweep.cpp
  cEpiabm/src/sweeps/spatial_sweep.hpp
  cEpiabm/test/CMakeLists.txt
  cEpiabm/test/dataclasses/test_cell.cpp
  cEpiabm/test/sweeps/test_spatial_sweep.cpp
  cEpiabm/test/test_covidsim.cpp
Labels: enhancement, C++

#56 Py file inputter
  README.md
  pyEpiabm/docs/source/routines.rst
  pyEpiabm/pyEpiabm/core/cell.py
  pyEpiabm/pyEpiabm/core/microcell.py
  pyEpiabm/pyEpiabm/routine/__init__.py
  pyEpiabm/pyEpiabm/routine/abstract_population_config.py
  pyEpiabm/pyEpiabm/routine/file_population_config.py
  pyEpiabm/pyEpiabm/routine/toy_population_config.py
  pyEpiabm/pyEpiabm/tests/test_core/test_microcell.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_abstract_population_config.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_file_population_config.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_toy_population_config.py
  pyEpiabm/requirements.txt
  pyEpiabm/setup.py
  python_examples/spatial_example/input.csv
  python_examples/spatial_example/spatial_simulation_flow.py
  python_examples/spatial_example/voronoi_plotting_example.py
Labels: enhancement, python

#61 Py improved gifs
  python_examples/spatial_example/spatial_outputs/voronoi_animation.gif
  python_examples/spatial_example/voronoi_plotting_example.py
Labels: frontend

#62 Raise missing households error (Issue #26)
  pyEpiabm/pyEpiabm/sweep/household_sweep.py
  pyEpiabm/pyEpiabm/tests/test_sweep/test_household_sweep.py
Labels: bug, python

#66 Wrapped distance function for configuration
  pyEpiabm/pyEpiabm/sweep/spatial_sweep.py
  pyEpiabm/pyEpiabm/tests/test_utility/test_distance_metrics.py
  pyEpiabm/pyEpiabm/utility/distance_metrics.py
Labels: python, refactor

#67 Progress bar (#64)
  pyEpiabm/pyEpiabm/routine/simulation.py
  pyEpiabm/pyEpiabm/tests/test_routine/test_simulation.py
  pyEpiabm/requirements.txt
  pyEpiabm/setup.py
Labels: enhancement, python
